# Generated by Django 5.2.5 on 2025-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_facts_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='topic',
            field=models.CharField(default='', max_length=120),
        ),
    ]
